### ISSUE TITLE
It does not work currently for multi file gists

### ISSUE THREAD

**Issue by shashank-k** [inkdropapp/inkdrop-embed#1]
Hi,

Thanks for building this. Currently it does not work with multi file gists. For example, this does not work. 

[embed]
(https://gist.github.com/peacefullatom/5e5d64f1aa4fdc2090dfeb39d7ef6463#file-gear-html)

**Comment by craftzdog** [comment]
Unfortunately GitHub does not support it.
PR for the workaround would be appreciated.
